[package]
name = "zelkova"
version = "0.0.0"
edition = "2021"

[dependencies]
bytemuck = { default-features = false, version = "1.13.0" }
pollster = { default-features = false, version = "0.3.0" }
wgpu = { default-features = false, features = ["wgsl"], version = "0.15.1" }
